### ISSUE TITLE
Error importing StreamTextures2D

### ISSUE THREAD

**Issue by sairam4123** [bruvzg/gdsdecomp#37]
While decompiling my friend's game (for fun), I found that there're some export errors with StreamTexture2D. Here's what I have found.
```
ERROR: Resource F:/Downloads/GDRE_tools-standalone-windows/Test-Woodland/ does not exist
   at: (modules\gdsdecomp\utility\gdre_settings.cpp:369)
ERROR: Can't open texture file
   at: (modules\gdsdecomp\utility\texture_loader_compat.cpp:29)
WARNING: Failed to load texture StreamTexture2D
     at: ImportExporter::export_imports (modules\gdsdecomp\utility\import_exporter.cpp:337)
```
Hopefully it should help.

**Comment by sairam4123** [comment]
I also found that this syntax isn't supported properly.
```
class Name extends Base:
```

**Comment by nikitalita** [comment]
Can you post the game that you're trying to decompile? This doesn't tell us much. Also, is this a Godot 2.x game or 3.x?

**Comment by sairam4123** [comment]
3.x Game. Godot 3.4.0 to be accurate.On 14-Dec-2021 6:22 AM, nikitalita ***@***.***> wrote:
Can you post the game that you're trying to decompile? This doesn't tell us much. Also, is this a Godot 2.x game or 3.x?

**Comment by nikitalita** [comment]
unfortunately, I'm not going to be able to do much until I have the game, as I've tested texture export on 3.4 and it works fine.

**Comment by nikitalita** [comment]
> I also found that this syntax isn't supported properly.
> 
> ```
> class Name extends Base: # It is being exported as class Nameextends Base:
> ```

this was fixed in #40

**Comment by sairam4123** [comment]
I tried on this game and I was able to reproduce this issue.
https://store.steampowered.com/app/1419150/Woodland_Empire/
I'll try again today.

**Comment by sairam4123** [comment]
I'm able to reproduce this issue, but unable to share the logs as text.
I have uploaded it as a file.
[output.txt](https://github.com/bruvzg/gdsdecomp/files/7729931/output.txt)

**Comment by nikitalita** [comment]
d'oh, this was a bug I had fixed on another branch but hadn't PRed yet, I'll do that now.

**Comment by sairam4123** [comment]
StreamTexture2D still isn't being exported..
```
Did not convert StreamTexture2D resource res://.import/slot0_normal_roughness.packed_tex-74d105433912d55960197f1e81f5c031.s3tc.stex
Did not convert StreamTexture2D resource res://.import/slot1_albedo_bump.packed_tex-c50964103f6881a306e97da81b332dcd.s3tc.stex
Did not convert StreamTexture2D resource res://.import/slot1_normal_roughness.packed_tex-631aea85a8c6aa800fb0f7ed84b54efb.s3tc.stex
```

Tried it on my own game.
```
Totals:
Imports for export session:     93
Successfully converted:                 72
Lossy:          0
Rewrote metadata: 0
Require rewritten metadata but weren't: 49
Not converted: 15
Failed conversions: 6
```

Tried again on my another game:
```
*********EXPORT REPORT***********
Totals:
Imports for export session:     26
Successfully converted:                 24
Lossy:          0
Rewrote metadata: 0
Require rewritten metadata but weren't: 6
Not converted: 1
Failed conversions: 1
-------------


The following files were converted and saved to a non-original path, but did not have their import data rewritten.
These files will not be re-imported when loading the project.
res://.import/add-white-18dp.svg-06b50d941748dbfd6e0203dec68494ea.stex to res://.assets/addons/imjp94.yafsm/assets/icons/add-white-18dp.png
res://.import/arrow_right-white-18dp.svg-10d349447e9bd513637eade1f10225f0.stex to res://.assets/addons/imjp94.yafsm/assets/icons/arrow_right-white-18dp.png
res://.import/close-white-18dp.svg-3d0e2341eb99a6dc45a6aecef969301b.stex to res://.assets/addons/imjp94.yafsm/assets/icons/close-white-18dp.png
res://.import/compare_arrows-white-18dp.svg-7313ec3b54f05c948521b16e0efaaeed.stex to res://.assets/addons/imjp94.yafsm/assets/icons/compare_arrows-white-18dp.png
res://.import/remove-white-18dp.svg-984af3406d3d64ea0f778da7f0f5a4c3.stex to res://.assets/addons/imjp94.yafsm/assets/icons/remove-white-18dp.png
res://.import/subdirectory_arrow_right-white-18dp.svg-09b2961410e6b2c0e48e0cf1138c3548.stex to res://.assets/addons/imjp94.yafsm/assets/icons/subdirectory_arrow_right-white-18dp.png

The following files were not converted because support has not been implemented yet:
res://.import/Sleeper_Coach.glb-fa6495d1fc0f39b483956912df51ce7d.scn

Failed conversions:
res://.import/icon.png-487276ed1e3a0c39cad0279d744ee560.s3tc.stex
*********************************
```
it still has issues..

**Comment by nikitalita** [comment]
We don't support `packed_tex` textures. As for the others, I'm gonna need to see the full `gdre_export.log`, which is located in the directory where you dumped the game. Just attach them to the issue.

**Comment by sairam4123** [comment]
Added the log, could you give it a check?

**Comment by nikitalita** [comment]
This looks like a bug on Godot's part. Apparently the icon was imported in a very strange way; if it's imported and stored as a compressed format, it's supposed to be able to uncompress it, but it can't here. Can you post the game somewhere so I can take a look?

**Comment by sairam4123** [comment]
Sure, you can download it from (here)[https://sairam4123.itch.io/openskycity].
